name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pipenv
        run: pip install pipenv --upgrade

      - name: Install dependencies
        run: pipenv install --system

      - name: Run Django Company API tests
        run: pytest api/coronavstech -s -v --durations=0 --cov=. -m "not skip_in_ci"

      - name: Run Fibonacci tests
        run: pytest fibonacci/ -s -v --durations=0 --cov=.
